### ISSUE TITLE
Tags Missing from Haystack Examples

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/brick-examples#2]
Hey Brickers - 

I've been going through the [ghausi](https://github.com/BrickSchema/brick-examples/blob/master/haystack/ghausi.json) example as a first pass and wanted to relay some issues I noticed in the Haystack tagging:

1. No "fcu" tags on any of the fan coil entities (FCU found in navName)
2. There are no "point" tags applied to entities:
  - "sensor" entities exist
  - "cmd" entities exist
  - "sp" entities exist
  - My assumption is these entities should have the "point" tag?

If I create a new branch and push the changes back (basically just to add "fcu": "M" and "point": "M") to the correct entities, does that work?  You can then merge as desired?

**Comment by gtfierro** [comment]
An important aspect of the `ghausi` example is that it is a real-world Haystack model: this is how the building was actually tagged by the building managers/consultants/engineers that worked on the building. As such, its an important artifact to preserve because it is an example of how Haystack is unable to enforce any consistency in the modelling of a building. Do you think you could file the improved ghausi model under a different name, e.g. "ghausi-v2", with a README noting the changes that were made?

**Comment by corymosiman12** [comment]
Yeah I can do that.  I think it's a little unfair though to say that Haystack is 'unable' to enforce consistency...it doesn't enforce consistency, but it also doesn't claim to.  The question is whether or not Haystack validation should be part of the Project Haystack development effort, or whether that should be up to vendor toolings to ensure conformance with the Haystack spec.

But yes, I do totally agree, limited reference examples out in the world make it difficult, and I've often found the Haystack documentation difficult to follow / understand.  This hopefully is significantly easier with Haystack 4.0!

**Comment by gtfierro** [comment]
What I mean by "unable to" is that the Haystack data model has fundamental ambiguities that make it difficult to enforce consistency. Haystack v4 introduces complexity for the sake of simplifying the process of generating documentation, but still doesn't have a formal specification for how the semantics of the model actually behave. The "ontology" they advertise is also only a syntactical representation of Haystack in the RDF data model -- not an actual ontology.

That said, it would be great to have an idiomatic version of the Ghausi Haystack model! You should fork the repository to your own account, push the changes, and then submit a pull request through the web interface (after you push to your own branch, the button should show up automatically, but let me know if you run into any problems). My only request is that you push the changes into a new "ghausi-idiomatic" or "ghausi-improved" file rather than replacing the existing model.

**Comment by gtfierro** [comment]
Closing due to https://github.com/BrickSchema/brick-examples/pull/3 being merged
